version: '3.8'

services:
  api:
    image: ghcr.io/madebaruna/paimon-moe-discord-bot:latest
    restart: always
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_COMMAND_PREFIX: ${DISCORD_COMMAND_PREFIX}
      TWITTER_TOKEN: ${TWITTER_TOKEN}
      REDIS_URL: ${REDIS_URL}
      PAIMON_MOE_SERVER_ID: ${PAIMON_MOE_SERVER_ID}
    volumes:
      - type: bind
        source: /home/baruna/server/paimon-moe-discord-bot/messages.json
        target: /bot/src/messages.json

  redis:
    image: redis:6.2.6-alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
