name: lint-build
on: [push]

jobs:
  lint-and-typecheck:
    name: Lint and typecheck codes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pnpm
        run: sudo npm i -g pnpm
      - name: Install modules
        run: pnpm install
      - name: Run linter
        run: pnpm run lint
      - name: Run typecheck
        run: pnpm run typecheck

  build-docker-image:
    name: Build docker image
    needs: lint-and-typecheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/madebaruna/paimon-moe-discord-bot:${{ steps.vars.outputs.sha_short }},ghcr.io/madebaruna/paimon-moe-discord-bot:latest

  deploy:
    name: Deploy to server
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
    - name: Run docker compose
      uses: appleboy/ssh-action@master
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        TWITTER_TOKEN: ${{ secrets.TWITTER_TOKEN }}
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script_stop: true
        envs: DISCORD_TOKEN,TWITTER_TOKEN
        script: |
          mkdir -p ~/server/paimon-moe-discord-bot
          cd ~/server/paimon-moe-discord-bot
          rm -f docker-compose.yml
          wget https://raw.githubusercontent.com/MadeBaruna/paimon-moe-discord-bot/main/docker-compose.yml
          rm -f .env
          touch .env
          echo "DISCORD_TOKEN=$DISCORD_TOKEN" >> .env
          echo "TWITTER_TOKEN=$TWITTER_TOKEN" >> .env
          sudo docker-compose pull 
          sudo docker-compose up -d
